### ISSUE TITLE
Sensors Unavailable

### ISSUE THREAD

**Issue by ZJGardner** [pyalarmdotcom/alarmdotcom#285] opened 2023-05-30 00:04 UTC
I'm new to Home Assistant, so I may be missing something simple. I've added the Alarmdotcom integration, and can see all of my sensors. I'm also able to activate and deactivate my alarm. The issue I'm having is, I cannot see the state of any of the sensors. They are all showing as "Unavailable."

I've attached a log of one of my sensors if this helps:

This error originated from a custom integration.

Logger: custom_components.alarmdotcom
Source: custom_components/alarmdotcom/__init__.py:158
Integration: Alarm.com (documentation, issues)
First occurred: 7:59:05 PM (2 occurrences)
Last logged: 7:59:05 PM

ALARM.COM DEBUG DATA FOR BACK DOOR: {"deviceType": 1, "openClosedStatus": 2, "state": 0, "isFlexIO": false, "deviceRole": 0, "displayStateText": "Not Monitored", "isMonitoringEnabled": false, "sensorNamingFormat": 4, "supportsBypass": false, "supportsImmediateBypass": false, "isBypassed": false, "managedDeviceType": 12, "hasState": true, "canBeRenamed": true, "canBeDeleted": false, "canAccessWebSettings": true, "canAccessAppSettings": false, "webSettings": 400, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "addDeviceResource": 0, "canBeAssociatedToVideoDevice": true, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isAssignedToCareReceiver": false, "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "BACK DOOR", "deviceModelId": 110, "canConfirmStateChange": true, "canReceiveCommands": false, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 317}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}

**Comment by elahd** [comment] 2023-05-31 04:09
Dupe of #241

**Closed** 2023-05-31 04:09 UTC
