### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by reyrios** [pyalarmdotcom/alarmdotcom#162] opened 2022-08-10 22:10 UTC
At first i thought it was the 8.3 version of HA but I get the same things on 8.2.  Even if I delete the integration and add it again.

Retrying setup: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.alarm.com/web/api/video/cameras/')

**Comment by elahd** [comment] 2022-08-11 14:05
Dupe of #163

**Closed by elahd** 2022-08-11 14:05 UTC
