### ISSUE TITLE
Alarm state not updating

### ISSUE THREAD

**Issue by fwedler** [pyalarmdotcom/alarmdotcom#243] opened 2023-03-29 00:21 UTC
First noticed with v2.2.2 and roil back to 2.2.1 but the issue persists.
The alarm arm/disarm state is not updating after a change in the arming state. If I manually reload the integration, then the state is updated. It will usually work for a short time after that but then goes back to not updating. The integration is using a dedicated read-only login separate from any other user account.
I see 2 related error logs:

```
Connection error while fetching trouble conditions.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.SYSTEM. User is already logged in. Giving up on device type.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.PARTITION. User is already logged in. Giving up on device type.
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.SENSOR. User is already logged in. Giving up on device type.
```

```
Unexpected error fetching Watchlight Corporation:homeassistant@opendrives.com data:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.155.71.71', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 871, in _async_get_trouble_conditions
    async with self._websession.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.alarm.com:443 ssl:default [Connect call failed ('192.155.71.71', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alarmdotcom/alarmhub.py", line 211, in async_update
    await self.system.async_update()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 347, in async_update
    await self._async_get_trouble_conditions()
  File "/usr/local/lib/python3.10/site-packages/pyalarmdotcomajax/__init__.py", line 913, in _async_get_trouble_conditions
    raise DataFetchFailed from err
pyalarmdotcomajax.errors.DataFetchFa
```

**Comment by bkr1969** [comment] 2023-03-29 13:49
Same problem for the past few days. Additional log info:
```
Error doing job: Task exception was never retrieved
07:42:25 – (ERROR) Alarm.com (custom integration) - message first occurred at March 27, 2023 at 08:26:22 and shows up 4299 times
Error fetching data from Alarm.com. Got 403 status when fetching data for device type DeviceType.SYSTEM. User is already logged in. Giving up on device type.
07:42:25 – (ERROR) Alarm.com (custom integration) - message first occurred at March 27, 2023 at 08:26:22 and shows up 12897 times
custom_components.alarmdotcom.base_device: No device data available for None (95356885-127).
07:42:01 – (ERROR) Alarm.com (custom integration) - message first occurred at March 28, 2023 at 09:14:21 and shows up 6 times
custom_components.alarmdotcom.alarmhub: Update failed: Cannot connect to host www.alarm.com:443 ssl:default [Try again]
March 27, 2023 at 20:51:02 – (ERROR) Alarm.com (custom integration) - message first occurred at March 27, 2023 at 09:54:25 and shows up 6 times
```

**Comment by CZX6** [comment] 2023-03-29 14:42
Also experiencing this same issue since the update to v2.2.2.

Created 2 scripts to add to Lovelace dashboard, Arm Home/Disarm.  I haven't established a timeline, but have to reload the integration occasionally (daily? every other day?) for the scripts to work.

**Comment by bkr1969** [comment] 2023-03-29 17:01
It seems we are just waiting for an update release. FWIW, in the meantime I've just added a configuration reset service call before any arm/disarm action (all my automations are via Node Red, but the same service call can be made directly in HA automations).  This has made it work so far.

**Comment by ssambhi900** [comment] 2023-04-17 16:15
Any updates on this issue?  This is causing issues... our automations that are triggered based on alarm status aren't activating/deactivating properly anymore!

**Comment by krisf12** [comment] 2023-04-17 16:49
I'm also having issues with the state of my lock not updating anymore

**Comment by fwedler** [comment] 2023-04-17 17:19
A temporary solution while waiting for the update is to use reload_config_entry on your alarm partition entity on a regular schedule. I am using every 2 hours in a node-red automation.

**Comment by jwfox5150** [comment] 2023-04-17 21:24
you don't need to even use node-red, you can just use homeassistant.reload_config_entry in an automation with a time_pattern trigger.

**Comment by rspierenburg** [comment] 2023-04-19 01:47
The same thing seems to be happening with contact sensors. My doors are showing as constantly open even though they are clearly closed.

**Comment by Raul-7-7** [comment] 2023-04-20 00:37
Another solution is to just downgrade to 2.2.0. It has been running rock solid for me (2+ weeks)

**Comment by bkr1969** [comment] 2023-04-20 16:22
What is the procedure for rolling back?

**Comment by Raul-7-7** [comment] 2023-04-20 17:59
@bkr1969 if you installed via hacks, go to the integration -> Re-download -> select 2.2.0 as your version. 
https://hacs.xyz/docs/faq/select_version/ for more info.

**Comment by elahd** [comment] 2023-05-13 16:42
Dupe of #234. Subscribe to that issue to track.

**Closed by elahd** 2023-05-13 16:42 UTC
