### ISSUE TITLE
Back to not updating status of alarm panel

### ISSUE THREAD

**Issue by bkr1969** [pyalarmdotcom/alarmdotcom#289] opened 2023-06-01 14:22 UTC
Updated to 3.0.2 yesterday and my panel status does not update nor is it arming/disarming even after a config entry reset. Seems to be an issue with the .2 as downgrading to 3.0.0 works.

**Comment by bkr1969** [comment] 2023-06-01 14:25
```
Unable to find referenced entities alarm_control_panel.panel or it is/they are currently not available
08:23:05 – (WARNING) helpers/service.py - message first occurred at 08:18:17 and shows up 17 times
Error unloading entry Brinks Home™:Brian@brianredmond.net for alarmdotcom
08:21:28 – (ERROR) Alarm.com (custom integration)
Error unloading entry Brinks Home™:Brian@brianredmond.net for alarm_control_panel
08:15:00 – (ERROR) Alarm.com (custom integration) - message first occurred at 08:15:00 and shows up 3 times
```

**Comment by elahd** [comment] 2023-06-01 19:20
v3.0.3 addresses _an_ issue with alarm control panel states. Please try that.

**Comment by bkr1969** [comment] 2023-06-01 21:19
OK. That seemed to fix it.  3.0.0 worked for a bit but then stopped again.  Hopefully this fixes everything moving forward.  Thanks!

**Comment by lbreggi** [comment] 2023-06-01 22:33
I just tried the 3.0.3 version and the panel looks like is working normal again but the locks are not updating. Is there anything I can do to help? Thanks!

**Comment by sspaul1976** [comment] 2023-06-02 13:09
I am seeing similar issues in 3.0.3. Doors now take up to 2 minutes to change Open/Close state. I tried on only one door at time and left open for over 3 minutes per release notes about same door not updating if multiple events in that timeframe.

**Comment by elahd** [comment] 2023-06-02 15:08
Does the app update any faster than the integration?

**Comment by sspaul1976** [comment] 2023-06-02 18:01
Actually, I just checked that.  The delay is in the app as well, but they
are synced up when it does change. So issue is on the alarm.com side.

**Comment by bkr1969** [comment] 2023-06-02 19:16
Doesn't make sense that it's an alarm.com issue.  Prior iterations updated immediately (i.e. running 2.2.0 last week), and after updating to 3.0.3, does the same.

**Comment by lbreggi** [comment] 2023-06-02 21:12
I can confirm that changes are real time reflected inside alarm.com app but not at hass. Also I tried to issue the lock / unlock command inside hass, it works, it is reflected at alarm.com app but the status inside hass takes around 10 minutes to get updated. Thanks!

**Comment by elahd** [comment] 2023-06-03 01:31
These are two separate issues. Some alarm panels on some providers take a
long time to update. If, like @sspaul1976, you're seeing the app and hass
update at the same time, then you're running into a limitation on the
Alarm.com side. If both platforms are out of sync, then you're running into
an issue with the integration.

**Comment by lbreggi** [comment] 2023-06-03 02:10
In my situation, I can confirm that the alarm.com app reflects updates like real time, and it was like that on the 2.x version of the HASS integration, since I moved to 3.X I have the delays. Thanks!

**Comment by thomasshawn** [comment] 2023-06-03 10:36
I can confirm that my panel updates immediately, but my alarm. Com app takes minutes to update sensors. If I arm or disarm it's immediate, but I was troubleshooting a window sensor yesterday and noticed the app takes minutes to update the status of the sensor. So I'm not sure it's this integration that's the issue I think it's the alarm. Com infrastructure.

This is a change though. I've used the app in the past to troubleshoot sensors and it was almost immediately evident when a sensor was triggered. Yesterday, big delay, wasn't  able to use the app in this way due to whatever change was made.

**Comment by lbreggi** [comment] 2023-06-03 19:45
Apologies, but is there a way to roll back to 2.x version and keep it without updates everything was working amazing for me on 2.x version, and this integration was my main goal moving from Smarthings platform. Thanks!

**Comment by mbhforum** [comment] 2023-06-04 20:27
I am having the same lack of updates in HA/HaaS as well.  I lowered the update time to 60 seconds, but that doesn't seem to help.  FWIW, I am also using an alarm.com Homebridge plug-in and do not have those delays.

**Comment by elahd** [comment] 2023-06-05 04:41
@mbhforum @thomasshawn Do you see the same delays when using the `adc` stream function? See streaming live events at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool.

**Comment by thomasshawn** [comment] 2023-06-05 10:33
> @mbhforum @thomasshawn Do you see the same delays when using the `adc` stream function? See streaming live events at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool.

I have not tried. To be clear, I was not pointing out any significant delays in your integration with Home Assistant. My point was to say, in my case, any delays appeared to be coming from ADC, not from your integration. Standing next to my keypad, if I open the door, my keypad immediately responds. My ADC app however can take many minutes to show the change in the events tab of the app. The zone doesn't appear to matter. There is a significant delay in the passive receipt of the information. If I arm/disarm from the app, it is virtually instantaneous. 


So I was pointing out that ADC own app showed a significant delay, so I didn't know if there was any point chasing a "problem" in your integration if ADC own app was doing the same thing.  if I don't know if that helps.

**Comment by steveomg** [comment] 2023-06-06 21:17
Same here - no updates in UI.

**Comment by sspaul1976** [comment] 2023-06-07 02:14
I am back to seeing sync issues in HA.  I have a door that's been closed
for 10 minutes. Shows closed in ADC app, open in HA.

**Comment by elahd** [comment] 2023-06-08 04:01
Test out v3.0.4-beta.1.

**Comment by lbreggi** [comment] 2023-06-08 22:35
Testing and so far good feedback!

**Comment by sspaul1976** [comment] 2023-06-09 13:20
I'm still seeing a delay. Does the alarm monitoring company have any
impacts on how this works? I am using Frontpoint.

**Closed** 2023-06-09 16:55 UTC
