### ISSUE TITLE
Updating state for binary_sensor.back_door_malfunction

### ISSUE THREAD

**Issue by vlape** [pyalarmdotcom/alarmdotcom#252] opened 2023-04-16 03:46 UTC
The following was reported via HA logs

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:568
First occurred: 22:21:29 (1 occurrences)
Last logged: 22:21:29

Updating state for binary_sensor.back_door_malfunction (<class 'custom_components.alarmdotcom.binary_sensor.MalfunctionAttributeSensor'>) took 0.566 seconds. Please report it to the custom integration author.

Hardware: Home Assistant Yellow
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest

**Comment by elahd** [comment] 2023-05-13 16:43
Dupe of #234. Subscribe to that issue to track.

**Closed by elahd** 2023-05-13 16:43 UTC
