### ISSUE TITLE
Sensor Open/Close not being detected/logged

### ISSUE THREAD

**Issue by sspaul1976** [pyalarmdotcom/alarmdotcom#242] opened 2023-03-28 14:09 UTC
Hello,

I am having an issue getting door and window sensors to be updated with open/close in HA. It looks like the only time these events are logged is if a door or window is left in an open state when the integration does its refresh (currently have set to 15 seconds).  Any time I open and close a door in normal use, these are not being logged.

Below is the activity from this morning as seen from the alarm.com app.  None of these are in the HA logbook as occuring. 

![Screenshot_20230328-094915~2](https://user-images.githubusercontent.com/6181510/228263190-e904ffeb-1c6a-4b18-bd8e-542263ed3cf1.png)

![Screenshot_20230328-100309](https://user-images.githubusercontent.com/6181510/228263557-dc35245a-d871-4c05-b2a2-39c880957212.png)

![Screenshot_20230328-100255](https://user-images.githubusercontent.com/6181510/228263563-4e2d57fa-8a01-46b8-98d8-fd01144f5daa.png)

**Comment by sspaul1976** [comment] 2023-04-08 13:26
Thank you. This resulted in no change.  Issue still persists in either version.

**Comment by Raul-7-7** [comment] 2023-04-08 18:12
@sspaul1976 remember there is a 30 second or so delay in updating, which means if you open and close the door in like 5 seconds, this wont be logged by HA.

**Comment by sspaul1976** [comment] 2023-04-13 22:11
So is this saying that by design, this integration will not capture open/close events when used in normal operation?  Meaning, it is only going to capture open of the sensor is actively in that state when the refresh occurs?

**Comment by Raul-7-7** [comment] 2023-04-13 22:20
@sspaul1976 that is correct, right now integration updates every 30 seconds, so if you open the door and close between the update it would not detect any change. I believe there is work being done to increase the frequency.

**Comment by elahd** [comment] 2023-05-13 16:42
Dupe of #234. Subscribe to that issue to track.

**Closed by elahd** 2023-05-13 16:42 UTC
