### ISSUE TITLE
Reloading integration every couple days

### ISSUE THREAD

**Issue by PerfectBake420** [pyalarmdotcom/alarmdotcom#380] opened 2024-02-21 23:20 UTC
Using home assistant automations I have automation set up to arm different partitions. I have a total of 4 accounts signed into the alarm.com integration.

The issue first began with the automation, saying they ran. However, and alarm.com never showed any activity. At that time, the integration still showed as loaded.

Over the last couple of weeks I have had to reload the alarm.com. Vation, every few days. It does not show the keypads on the dashboard until I reload it.

I am currently using Integration version 3.10.0, Core 2024.1.6, Supervisor 2024.02.0, and OS 10.5.

If there's any more information I can give to you please ask.
Thank you

**Comment by elahd** [comment] 2024-03-04 19:22
This sounds similar to #381. Let's merge and track there.

Duplicate of #381

**Comment by elahd** [comment] 2024-03-04 19:22
Duplicate of #381

**Closed by elahd** 2024-03-04 19:22 UTC
Labels: bug
