### ISSUE TITLE
All sensors unavailable

### ISSUE THREAD

**Issue by farberm** [pyalarmdotcom/alarmdotcom#281] opened 2023-05-28 14:33 UTC
I have tried removing the custom component folder and reinstalling with ver 2 and beta version 3 but still the same. All my sensors read unavailable? All of my zones are present but how do I monitor the sensors? 
<img width="1085" alt="Screenshot 2023-05-28 at 10 26 51 AM" src="https://github.com/pyalarmdotcom/alarmdotcom/assets/16128857/80dce96a-431a-4622-b590-e5800f4fd3d5">

**Comment by elahd** [comment] 2023-05-28 17:16
Can you let me know if this is still an issue with v3.0.1? If it is, can you post the sensor data for one of your sensors using [these instructions](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#get-debug-data-for-a-single-entity)?

**Comment by farberm** [comment] 2023-05-28 22:21
Does not work with 3.0.1…here is the debug log for one of themThis error originated from a custom integration.Logger: custom_components.alarmdotcomSource: custom_components/alarmdotcom/__init__.py:158 Integration: Alarm.com (documentation, issues) First occurred: 6:19:46 PM (1 occurrences) Last logged: 6:19:46 PMALARM.COM DEBUG DATA FOR BASEMENT BACK DOOR: {"deviceType": 1, "openClosedStatus": 2, "state": 0, "isFlexIO": false, "deviceRole": 0, "displayStateText": "Not Monitored", "isMonitoringEnabled": false, "sensorNamingFormat": 4, "supportsBypass": false, "supportsImmediateBypass": false, "isBypassed": false, "managedDeviceType": 12, "hasState": true, "canBeRenamed": true, "canBeDeleted": false, "canAccessWebSettings": true, "canAccessAppSettings": false, "webSettings": 400, "canAccessTroubleshootingWizard": false, "troubleshootingWizard": null, "addDeviceResource": 0, "canBeAssociatedToVideoDevice": true, "associatedCameraDeviceIds": {}, "macAddress": "", "manufacturer": "", "isAssignedToCareReceiver": false, "isOAuth": false, "isZWave": false, "supportsCommandClassBasic": false, "isMalfunctioning": false, "canBeSaved": true, "canChangeDescription": true, "description": "BASEMENT BACK DOOR", "deviceModelId": 110, "canConfirmStateChange": true, "canReceiveCommands": false, "remoteCommandsEnabled": true, "hasPermissionToChangeState": true, "deviceIcon": {"icon": 317}, "batteryLevelNull": null, "lowBattery": false, "criticalBattery": false}Sent from my iPadOn May 28, 2023, at 1:16 PM, Elahd Bar-Shai ***@***.***> wrote:﻿
Can you let me know if this is still an issue with v3.0.1? If it is, can you post the sensor data for one of your sensors using these instructions?

**Comment by elahd** [comment] 2023-05-30 02:16
Alarm.com is reporting an unknown state for the sensor (`"state": 0`). It also looks like the sensors aren't being monitored (`"isMonitoringEnabled": false`). What do you see at https://www.alarm.com/web/Security/Sensors.aspx?

**Comment by farberm** [comment] 2023-05-30 02:22
Here is a screenshot of website. They state status ok and are monitored…Sent from my iPhoneOn May 29, 2023, at 10:16 PM, Elahd Bar-Shai ***@***.***> wrote:﻿
Alarm.com is reporting an unknown state for the sensor ("state": 0). It also looks like the sensors aren't being monitored ("isMonitoringEnabled": false). What do you see at https://www.alarm.com/web/Security/Sensors.aspx?

**Comment by elahd** [comment] 2023-05-30 20:21
Do you have multiple partitions or systems?

**Comment by farberm** [comment] 2023-05-30 20:48
I am pretty sure I only have one partition but not sure how to check to conform. I only have one alarm system. The fire and panic sensors seems to register fine?Sent from my iPhoneOn May 30, 2023, at 4:22 PM, Elahd Bar-Shai ***@***.***> wrote:﻿
Do you have multiple partitions or systems?

**Comment by elahd** [comment] 2023-05-31 04:18
Thanks. I'm going to mark this as a duplicate of #241.

You can check your systems and partitions using the adc command line tool. Follow the instruction [here](https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#install-the-adc-command-line-tool) to install the tool, then run the "Basic" command from the table. Check under the Systems and Partitions sections and post what you see in #241.

**Closed by elahd** 2023-05-31 04:18 UTC
