### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by sceccola** [pyalarmdotcom/alarmdotcom#263] opened 2023-05-12 11:35 UTC
my panel will not arm via script or lovelace.. please help

**Comment by jkevinburton** [comment] 2023-05-13 03:29
I also noticed in the last week that I needed to reload the integration in order for it to work again in HA.

**Comment by elahd** [comment] 2023-05-13 16:40
Dupe of #234. Track there.

**Closed by elahd** 2023-05-13 16:40 UTC
